name: theraconsulting-cesar
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=theraconsultingcesar
    ports:
      - 6500:5432
    volumes:
      - db:/data/postgres
  seed:
    container_name: seed
    depends_on:
      - db
    build:
      context: .
      dockerfile: seed/Dockerfile
    volumes:
      - .:/seed
    command:  /bin/sh -c "chmod +x seed/seed.sh && seed/seed.sh"
  app:
    container_name: app
    depends_on:
      - seed
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - .:/app
volumes:
  db:
