name: theraconsulting-cesar
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=theraconsultingcesar
    ports:
      - 6500:5432
    volumes:
      - db:/data/postgres
volumes:
  db:
